### ISSUE TITLE
libai 新建projects教程

### ISSUE THREAD

**Issue by CPFLAME** [Oneflow-Inc/libai#29]
### 需求

如果开发者想进行新任务的开发(比如论文复现, finetune task的添加), 那么基于`libai`的库, 怎么实现最少的代码开发工作?

首先我们必须明确的是基于`libai`去进行新任务的开发, 有什么样的好处:

1. 对于`libai`来说: 新添加的代码工作可以和`libai`的框架代码隔离开, 不干扰`libai`的框架代码的正确性, 避免和其他模块冲突, 引入未知bug, 而且可以最大程度保持`libai`框架的简洁性, 不会越来越臃肿
2. 对于用户来说: `libai`的很多特性在projects里面都可以继承, 不用自己重新造轮子, 比如
    - 用户可以继承`libai`的`trainer`和`lazyconfig`, 只需要自己重构`model`和`dataloader`, 可以实现代码最小化.
    - 用户可以享受到`libai`的特性: `libai`会保存配置文件, 可以很快地复现自己跑过的实验; `libai`在训练期间输出多样化的训练信息, 比如剩余训练时间, 当前iter进度, 吞吐量, loss信息, 当前learning rate等 

models组的实习生也可以基于`libai`这个框架, 每一个模型复现的任务独立开发一个projects, 方便于代码的整合与管理

### 新建任务

我们以新建一个bert_finetune的task为例, 整体代码可见[projects_demo](https://github.com/Oneflow-Inc/libai/tree/projects_finetune_qqp/projects)

首先我们来看整体的结构, 对于一个新建的任务来说, 我们主要的工作其实在于:
1. 编写`config.py`, 这个config是该任务独立的config, 不会干扰到其他的task和libai库
2. 编写`model.py`, 与新建任务的模型相关
3. 编写`dataloader.py`, 与新建模型的数据集相关

```
libai
    configs/
        ...
    libai/
        ...
    tests/
        ...
    tools/
        ...
    projects/
        your_task/
            dataset/
            model.py
            config.py
            finetune.py
```

#### 函数入口

我们先来看finetune.py, 这个程序是主要的函数入口, 用户的自定义模块将在此处进行重载
在程序中, 我们只需要重载get_batch函数, 和trainer中的'build_train_valid_test_loader()'

一个简单的样例
```python
import sys
import oneflow as flow

sys.path.append(".")
from your_dataset import build_train_valid_test_data_iterators

from libai.config import LazyConfig, default_argument_parser
from libai.utils import distributed as dist
from libai.utils.checkpoint import Checkpointer

from libai.trainer import DefaultTrainer, default_setup
import logging

# 用户需要自己重新定义get_batch函数, 函数的返回和model.forward()的入参匹配
def get_batch(data_iterator):
    """Build the batch."""

    if data_iterator is not None:
        data = next(data_iterator)
    else:
        data = None

    input_placement = dist.get_layer_placement(0)
    label_placement = dist.get_layer_placement(-1)
    sbp = dist.get_nd_sbp([flow.sbp.split(0), flow.sbp.broadcast])

    def to_consistent(tensor, placement):
        tensor = tensor.to_consistent(placement, sbp)
        return tensor

    # Unpack.
    tokens = to_consistent(data["text"].long(), input_placement)
    types = to_consistent(data["types"].long(), input_placement)
    padding_mask = to_consistent(data["padding_mask"].long(), input_placement)
    label = to_consistent(data["label"].long(), label_placement)

    return tokens, padding_mask, types, label

# 用户需要继承一下DefaultTrainer, 然后重载自己的dataloader函数
class Trainer(DefaultTrainer):
    @classmethod
    def build_train_valid_test_loader(cls, cfg):
        """
        Returns:
            iterable
        It now calls :func:`libai.data.build_reid_train_loader`.
        Overwrite it if you'd like a different data loader.
        """
        logger = logging.getLogger("libai."+__name__)
        logger.info("Prepare training set")
        return build_train_valid_test_data_iterators(cfg)
    

    def run_step(self):
        return super().run_step(get_batch)


def main(args):
    cfg = LazyConfig.load(args.config_file)
    cfg = LazyConfig.apply_overrides(cfg, args.opts)
    default_setup(cfg, args)

    if args.eval_only:
        model = Trainer.build_model(cfg)
        Checkpointer(model, save_dir=cfg.train.output_dir).resume_or_load(
            cfg.train.load_weight, resume=args.resume
        )
        graph = Trainer.build_graph(cfg, model, is_train=False)
        res = Trainer.test(cfg, graph)

    trainer = Trainer(cfg)
    return trainer.train()


if __name__ == "__main__":
    args = default_argument_parser().parse_args()
    main(args)

```

#### 重定义model

接下来我们定义`model.py`, 这里注意除了定义model之外, 我们还需要重新定义一下graph(继承`GraphBase`)
其中model在定义时, 尽可能的使用`libai.layers`下的模块, 里面有配套的的sbp, 用户可以直接使用, 不用管sbp的配置.

```python
from oneflow import nn
from libai.models.graph_bash import 


class MyModel(nn.Module):
    def __init__(self, cfg):
        ```
        这里的cfg里面的参数 对应config.py中的my_cfg
        ```
        ...

    def forward(self, tokens, padding_mask, types, label):
        ...
        return loss

class MyGraph(GraphBase):
    
    def build(self, tokens, padding_mask, types, label):
        ```
        这里入参和get_batch的返回值保持一致
        ```
        loss = self.model(tokens, padding_mask, types, label)
        loss.backward()
        return loss

    def set_activation_checkpoint(self):
        ```
        开启checkpointing, 如有需求, 可参考 libai.models.bert_model.py
        ```
        pass

    def set_pipeline_stage_id(self):
        ```
        流水并行设置stage_id, 如有需求, 可参考 libai.models.bert_model.py
        ```
        pass
```

#### 重新定义config

`libai`的`config`比较特殊, 采用`lazyconfig`的形式, 可以是`.py`文件, 在保存时会保存为`.yaml`, 后续星宇应该会专门写一个issue来描述`lazyconfig`的特性
在这里先简单的讲讲完整的`config.py`, 以及怎么继承`config.py`.

首先, 在训练的任务里面, `config.py`有几个必要的字段:
- `train`: 和训练相关的入参, 字典形式
- `model`: 和模型结构相关, 在`config`里面直接指定生成方式, 由于`lazyconfig`的特性, 会在程序运行时再生成model
- `data`: 和`dataloader`相关的入参, 字典形式
- `optim`: 和优化器相关, 在`config`里面直接指定生成方式, 同上
- `lr_scheduler`: 和学习率相关, 在`config`里面直接指定生成方式, 同上
- `graph`: 和graph模式相关(oneflow特有), 在`config`里面直接指定生成方式, 同上

基于以上的了解, 我们先来看看一个完整的`config.py`, 应该是什么样子, 

> 注意, 所有import的模块必须以libai的根目录为路径, 否则保存的`yaml`文件将无法保存模块的正确路径, 导致读取`yaml`报错从而不能复现实验

```python
from libai.config import LazyCall as L
from libai.model_path.model import BaseModel, BaseGraph
import oneflow as flow
from libai.optim import get_default_optimizer_params, PolynomialLR
from libai.config import LazyCall as L

train = dict(
    output_dir="./demo_output/test_config",
    start_iter=0,
    train_iter=10000,
    micro_batch_size=32,
    ...
)

data = dict(
    seq_length=512,
    tokenizer_type="BertCNWWMTokenizer",
    dataloader_type="single",
    num_workers=4,
    ...
)

my_cfg = dict(
    vocab_size=30522,
    hidden_size=768,
    hidden_layers=24,
    ...
)
model = L(BaseModel)(cfg=my_cfg)

# 众所周知optimizer在初始化的时候, 需要model.parameters()作为入参.
# 但是model还未构建, 拿不到parameters(), 由于lazyconfig的特性, 在此处只会更新optim的以下参数, 在程序中等拿到了model.parameters()再延迟构建 
optim = L(flow.optim.AdamW)(
    parameters=L(get_default_optimizer_params)(
        # parameters.model is meant to be set to the model object, before instantiating the optimizer.
        clip_grad_max_norm=1.0,
        clip_grad_norm_type=2.0,
        weight_decay_norm=0.0,
        weight_decay_bias=0.0,
    ),
    lr=1e-4,
    weight_decay=0.01,
    betas=(0.9, 0.999),
    do_bias_correction=True,
)

lr_scheduler = L(flow.optim.lr_scheduler.WarmUpLR)(
    lrsch_or_optimizer=L(PolynomialLR)(steps=1000, end_learning_rate=1.0e-5,),
    warmup_factor=0,
    warmup_iters=100,
    warmup_method="linear",
)

graph = dict(
    # options for graph or eager mode
    enabled=True,
    train=L(BaseGraph)(
        fp16=True,
        is_eval=False,
    ),
    eval=L(BaseGraph)(
        fp16=True, 
        is_eval=True,),
)
```

接下来我们讲讲怎么继承`config.py`, 可想而知的是, 我们做finetune任务, 大部分的config其实都和pretrain的任务一样, 我们只需要改少数几个参数就可以了.

在`config.py`中我们必须要有的六要素, 所以即使我们不需要改变某个要素, 我们也得把它import进来, 但不需要进行修改.

可以看到的是我们已经把model和graph的生成方式换成了自己的, 而且在train里面我们修改了老字段以及添加了新字段

```python
from libai.projects.model import MyModel, MyGraph
from libai.config_dir.confg import data
from libai.config_dir.confg import train
from libai.config_dir.confg import optim
from libai.config_dir.confg import lr_scheduler
from libai.config_dir.confg import my_cfg

my_cfg.update(
    dict(
        # exist key
        hidden_size=1024,
        # new key
        num_classes=2,
    )
)
model = L(Classification)(cfg=my_cfg)

train.update(
    dict(
        # exist key
        output_dir="output/finetune_qqp/",
        micro_batch_size=16,
        global_batch_size=16,
        train_iter=10000,
        # new key
        train_data=["/home/chengpeng/train.tsv",],
        valid_data=["/home/chengpeng/dev.tsv",],
    )
)

graph = dict(
    # options for graph or eager mode
    enabled=True,
    train=L(MyGraph)(
        fp16=True,
        is_eval=False,
    ),
    eval=L(MyGraph)(
        fp16=True, 
        is_eval=True,),
)
```

构建好`config.py`以后, 我们在程序中想拿到对应的字段, 只需要进行类似的访问`cfg.train.output_dir`即可.

### 重新定义dataloader

这个部分还没有完全的ready 当前重新定义dataloader的方式需要重载如下的函数:
    - `dataset.py`: 继承自`oneflow.utils.data.Dataset`
    - `build_train_valid_test_data_iterators()`: 供`finetune.py`中的trainer调用

详细的代码可以参见[projects_demo](https://github.com/Oneflow-Inc/libai/tree/projects_finetune_qqp/projects/QQP/)

### 开启训练

等上述的模块重载完以后, 我们就可以开启训练任务了.
`bash projects/finetune.sh`

> CONFIG可以同时支持py文件和生成的yaml文件
```bash
#!/usr/bin/env bash

CONFIG=projects/your_task/config.py #output/your_task/config.yaml
GPUS=1
NODE=1
NODE_RANK=0
PORT=2345

python3 -m oneflow.distributed.launch \
    --nproc_per_node $GPUS \
    --nnodes $NODE \
    --node_rank $NODE_RANK \
    --master_addr $PORT \
    projects/your_task/finetune.py \
    --config-file $CONFIG \
    --num-gpus $GPUS
```

**Comment by CPFLAME** [comment]
### 运行时的打印信息&&保存的config.yaml格式

运行时的打印信息:
![image](https://user-images.githubusercontent.com/13843079/147658924-a66b4f76-08ea-4d80-a489-c372544cbc87.png)

保存的config yaml文件:
```yaml
data:
  data_impl: mmap
  data_path: [/workspace/idea_model/idea_bert/output_data/loss_compara_content_sentence]
  dataloader_type: single
  dataset_type: bert
  decoder_seq_length: null
  encoder_seq_length: null
  eod_mask_loss: false
  make_vocab_size_divisible_by: 128
  mask_prob: 0.15
  merge_file: null
  mmap_warmup: true
  num_workers: 4
  reset_attention_mask: false
  reset_position_ids: false
  sample_rate: 1.0
  seq_length: 512
  short_seq_prob: 0.1
  split: 949,50,1
  tokenizer_setup: true
  tokenizer_type: BertCNWWMTokenizer
  use_external_dataset: false
  vocab_extra_ids: 0
  vocab_file: /home/chengpeng/PrimeLM/data/bert-base-chinese-vocab.txt
graph:
  enabled: true
  eval: {_target_: projects.QQP.modeling.model.ClassificationGraph, fp16: true, is_eval: true}
  train: {_target_: projects.QQP.modeling.model.ClassificationGraph, fp16: true, is_eval: false}
lr_scheduler:
  _target_: oneflow.nn.optimizer.warm_up_lr.WarmUpLR
  lrsch_or_optimizer: {_target_: libai.optim.PolynomialLR, end_learning_rate: 1.0e-05, steps: 1000}
  warmup_factor: 0
  warmup_iters: 100
  warmup_method: linear
model:
  _target_: projects.QQP.modeling.model.Classification
  cfg: {add_pooling_layer: true, apply_query_key_layer_scaling: true, attention_probs_dropout_prob: 0.1, bias_dropout_fusion: true, bias_gelu_fusion: true, hidden_dropout_prob: 0.1, hidden_layers: 24, hidden_size: 1024, initializer_range: 0.02, intermediate_size: 4096, layernorm_eps: 1.0e-05, max_position_embeddings: 512, num_attention_heads: 16, num_classes: 2, num_tokentypes: 2, pretrain_megatron_weight: /home/chengpeng/model_optim_rng.pt, scale_mask_softmax_fusion: false, vocab_size: 21248}
optim:
  _target_: oneflow.nn.optimizer.adamw.AdamW
  betas: [0.9, 0.999]
  do_bias_correction: true
  lr: 0.0001
  parameters: {_target_: libai.optim.get_default_optimizer_params, clip_grad_max_norm: 1.0, clip_grad_norm_type: 2.0, weight_decay_bias: 0.0, weight_decay_norm: 0.0}
  weight_decay: 0.01
qqp_cfg: {add_pooling_layer: true, apply_query_key_layer_scaling: true, attention_probs_dropout_prob: 0.1, bias_dropout_fusion: true, bias_gelu_fusion: true, hidden_dropout_prob: 0.1, hidden_layers: 24, hidden_size: 1024, initializer_range: 0.02, intermediate_size: 4096, layernorm_eps: 1.0e-05, max_position_embeddings: 512, num_attention_heads: 16, num_classes: 2, num_tokentypes: 2, pretrain_megatron_weight: /home/chengpeng/model_optim_rng.pt, scale_mask_softmax_fusion: false, vocab_size: 30522}
train:
  amp: {enabled: false}
  checkpointer: {max_to_keep: 100, period: 5000}
  consumed_train_samples: 0
  consumed_valid_samples: 0
  dist: {data_parallel_size: 1, num_gpus_per_node: 1, num_nodes: 1, pipeline_num_layers: 24, pipeline_parallel_size: 1, tensor_parallel_size: 1}
  enable_use_compute_stream: true
  eval_iter: 10000
  eval_period: 5000
  global_batch_size: 16
  load_weight: ''
  log_period: 1
  lr_decay_iter: null
  lr_warmup_fraction: 0.01
  micro_batch_size: 16
  nccl_fusion_max_ops: 24
  nccl_fusion_threshold_mb: 16
  num_accumulation_steps: 1
  output_dir: output/finetune_qqp/
  resume: false
  seed: 1234
  start_iter: 0
  train_data: [/home/chengpeng/train.tsv]
  train_iter: 10000
  train_samples: null
  valid_data: [/home/chengpeng/dev.tsv]

```
